# Generated by Django 5.2 on 2025-04-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
