# Generated by Django 5.2 on 2025-04-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_attendance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='internship.attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='intern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='internship.intern'),
        ),
        migrations.AlterField(
            model_name='image',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='internship.task'),
        ),
    ]
