# Generated by Django 5.2 on 2025-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_remove_attendance_tasks_task_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('validated', 'Validated'), ('flagged', 'Flagged')], default='ongoing', max_length=10),
        ),
        migrations.AddField(
            model_name='intern',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('ongoing', 'Ongoing'), ('dropped', 'Dropped')], default='ongoing', max_length=10),
        ),
    ]
