# Generated by Django 5.2 on 2025-04-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_attendance_status_intern_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('validated', 'Validated'), ('flagged', 'Flagged'), ('sent', 'Sent')], default='ongoing', max_length=10),
        ),
    ]
