# Generated by Django 5.2 on 2025-04-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_attendance_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_duration',
            field=models.DurationField(default='0:00:00'),
        ),
    ]
