# Generated by Django 5.2 on 2025-04-12 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_attendance_work_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='remarks',
            new_name='admin_remarks',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='remarks',
            new_name='intern_remarks',
        ),
        migrations.AddField(
            model_name='intern',
            name='admin_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='status',
            field=models.CharField(choices=[('passed', 'Completed'), ('ongoing', 'Ongoing'), ('dropped', 'Dropped'), ('completed', 'Passed')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='intern',
            name='time_rendered',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
