# Generated by Django 5.2 on 2025-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_rename_remarks_attendance_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('validated', 'Validated'), ('flagged', 'Flagged'), ('sent', 'Sent')], default='f2f', max_length=10),
        ),
    ]
