# Generated by Django 5.2 on 2025-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_alter_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('f2f', 'F2f'), ('async', 'Async')], default='f2f', max_length=10),
        ),
    ]
